modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="slightlymoreores"
version="2.0"
displayName="SlightlyMoreOres"
displayURL="https://modrinth.com/mod/slightlymoreores"
logoFile="logo.png"
credits="Created with MCreator"
authors="Diablodesu"
description="Adds more ores to your minecraft world"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.slightlymoreores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration