modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"

[[mods]]
modId="slightlymoreores"
version="1.10"
displayName="SlightlyMoreOres"
displayURL="https://modrinth.com/mod/slightlymoreores"
logoFile="logo.png"
credits="Created with MCreator"
authors="Diablodesu"
description="Adds more ores to your minecraft world"

[[dependencies.slightlymoreores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




