modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="slightlymoreores"
version="1.4.0"
displayName="SlightlyMoreOres"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://modrinth.com/mod/slightlymoreores"
logoFile="logo.png"
authors="Diablodesu"
description='''
Adds more ores to your minecraft world
'''

[[dependencies.slightlymoreores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




